server:
  port: ${SERVER_PORT:10002}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://${EUREKA_HOSTNAME:localhost}:8761/discovery-server/

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOSTNAME:localhost}:3306/demo?tinyInt1isBit=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: jc
    password: jc
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 3
      maximum-pool-size: 24
      pool-name: ${spring.application.name}-CP
      idle-timeout: 10000
      leakDetectionThreshold: 2000

  redis:
   port: 6379
   host: ${REDIS_HOSTNAME:localhost}
   pool:
     maxIdle: 8 # max idle connections in the pool
     minIdle: 0 # min idle connections in the pool
     maxActive: -1 # no limit to the number of active connections
     maxWait: 30000 # time limit to get a connection - only applies if maxActive is finite

logging:
  level:
    org.mosquito.seed: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
