version: "3"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      MYSQL_USER: jc
      MYSQL_PASSWORD: jc
    volumes:
      - "../db/mysql:/docker-entrypoint-initdb.d"

