server:
  port: 8761
eureka:
  instance:
      hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-zone: http://${discoveryserver.instance.hostname}:${server.port}/discoveryserver/
