server:
  port: ${SERVER_PORT:8080}
zuul:
  routes:
    auth-center:
      path: /uaa/**
      serviceId: auth-center
    demo-backend:
      path: /demo/**
      serviceId: demo-backend
  sensitive-headers:
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOSTNAME:localhost}:8761/eureka/
logging:
  level:
    org.mosquito: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
oauth2-header-filter:
  ignore-paths: /uaa/**
