server:
  port: 8888
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://discovery-server:8761/eureka/
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jessie-chen/mosquito-seed-config-repo.git
