server:
  port: ${SERVER_PORT:8888}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOSTNAME:localhost}:8761/eureka/
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jessie-chen/mosquito-seed-config-repo.git
logging:
  level:
    com.netflix.discovery: DEBUG